### ISSUE TITLE
cargo workspace support

### ISSUE THREAD

**Issue by awestlake87** [koute/cargo-web#17]
I tried splitting a project into a cargo workspace, and found an odd issue. I separated my project into a local library crate that the main project depends on.

```toml
[package]
# ...

[workspace]
members = ["./local-lib"]

[dependencies]
local-lib = { path = "./local-lib" }
stdweb = "*"
```

after doing this, "cargo web start" throws the following error

```
$ cargo web start
error: cannot start a webserver for a crate which is a library!
```

I fixed it by removing the workspace section in the toml

```toml
[package]
# ...

[dependencies]
local-lib = { path = "./local-lib" }
stdweb = "*"
```

It seems like it thinks that the main project is a different type of crate when the workspace tag is set, but I think this is a perfectly valid setup for a workspace. is there any reason why cargo-web rejects this?

**Comment by emk** [comment]
I can also reproduce this, using `cargo-web` 0.2 and the Rust nightly from 2017-12-21.

If the web project is laid out as:

```
main_project
+-- Cargo.toml
+-- web_project
  +-- Cargo.toml
```

Then you may need to add the following to `main_project/Cargo.toml`:

```toml
[workspace]
exclude = ["web_project"]
```
