### ISSUE TITLE
Support dependencies in `Cargo.toml` gated with `cfg!`

### ISSUE THREAD

**Issue by koute** [koute/cargo-web#72]
Related: https://github.com/koute/stdweb/issues/135

**Comment by kuviman** [comment]
Hello, it looks like there is also an issue if the dependency is specified multiple times for different targets, like:

```toml
[target.wasm32-unknown-emscripten.dependencies]
stdweb = "*"
[target.asmjs-unknown-emscripten.dependencies]
stdweb = "*"
```

This way, stdweb's JavaScript is only prepended to asmjs output
