### ISSUE TITLE
[Question] Can I specify anyone of lib, bins, and examples in Cargo.toml?

### ISSUE THREAD

**Issue by y-ich** [koute/cargo-web#73]
Hi.
Thank you for your excellent framework.
I have a question for you.

My Cargo.toml is currently like the below for both native and wasm support.

```toml
[lib]
name = "common_lib" #target architecture independent library

[[bin]]
name = "native_exe" # native program using common_lib
path = "src/main.rs"

[[example]]
name = "wasm_lib" # wasm library providing common_lib for JS. It is an "example" since it is a library, not a executable.
path = "src/wasm.rs"
crate-type = ["cdylib"]
```

Can I specify to use the example "wasm_lib" in Web.toml?
By default, Web.toml seems to try to use the bin "native_exe".

Thanks.
