### ISSUE TITLE
Use Cargo configuration for default target

### ISSUE THREAD

**Issue by gheoan** [koute/cargo-web#84]
[Cargo configuration](https://doc.rust-lang.org/cargo/reference/config.html) should be used for default target instead of `Web.toml`.
Example: 
```toml
# .cargo/config
[build]
target = "wasm32-unknown-emscripten" 
```
